# Generated by Django 5.0.7 on 2024-07-18 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('SOLO', 'Solo'), ('BANDA', 'Banda')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistas.documento')),
            ],
        ),
    ]
