# Generated by Django 5.0.7 on 2024-07-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artista',
            name='tipo',
            field=models.CharField(choices=[('SOLO', 'Solo'), ('BANDA', 'Banda')], max_length=100),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('CPF', 'CPF'), ('RG', 'RG')], max_length=100),
        ),
    ]
