# Generated by Django 5.0.7 on 2024-07-18 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0002_alter_artista_id_alter_artista_tipo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='nome',
            new_name='numero',
        ),
    ]
