# Generated by Django 5.0.7 on 2024-07-18 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0003_rename_nome_documento_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='documento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artistas.documento'),
        ),
    ]
